 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prodution_events", type: :request do
  
  # ProdutionEvent. As you add validations to ProdutionEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProdutionEvent.create! valid_attributes
      get prodution_events_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prodution_event = ProdutionEvent.create! valid_attributes
      get prodution_event_url(prodution_event)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prodution_event_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      prodution_event = ProdutionEvent.create! valid_attributes
      get edit_prodution_event_url(prodution_event)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProdutionEvent" do
        expect {
          post prodution_events_url, params: { prodution_event: valid_attributes }
        }.to change(ProdutionEvent, :count).by(1)
      end

      it "redirects to the created prodution_event" do
        post prodution_events_url, params: { prodution_event: valid_attributes }
        expect(response).to redirect_to(prodution_event_url(ProdutionEvent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProdutionEvent" do
        expect {
          post prodution_events_url, params: { prodution_event: invalid_attributes }
        }.to change(ProdutionEvent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prodution_events_url, params: { prodution_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prodution_event" do
        prodution_event = ProdutionEvent.create! valid_attributes
        patch prodution_event_url(prodution_event), params: { prodution_event: new_attributes }
        prodution_event.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prodution_event" do
        prodution_event = ProdutionEvent.create! valid_attributes
        patch prodution_event_url(prodution_event), params: { prodution_event: new_attributes }
        prodution_event.reload
        expect(response).to redirect_to(prodution_event_url(prodution_event))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prodution_event = ProdutionEvent.create! valid_attributes
        patch prodution_event_url(prodution_event), params: { prodution_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prodution_event" do
      prodution_event = ProdutionEvent.create! valid_attributes
      expect {
        delete prodution_event_url(prodution_event)
      }.to change(ProdutionEvent, :count).by(-1)
    end

    it "redirects to the prodution_events list" do
      prodution_event = ProdutionEvent.create! valid_attributes
      delete prodution_event_url(prodution_event)
      expect(response).to redirect_to(prodution_events_url)
    end
  end
end
