 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prodution_jobs", type: :request do
  
  # ProdutionJob. As you add validations to ProdutionJob, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProdutionJob.create! valid_attributes
      get prodution_jobs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prodution_job = ProdutionJob.create! valid_attributes
      get prodution_job_url(prodution_job)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prodution_job_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      prodution_job = ProdutionJob.create! valid_attributes
      get edit_prodution_job_url(prodution_job)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProdutionJob" do
        expect {
          post prodution_jobs_url, params: { prodution_job: valid_attributes }
        }.to change(ProdutionJob, :count).by(1)
      end

      it "redirects to the created prodution_job" do
        post prodution_jobs_url, params: { prodution_job: valid_attributes }
        expect(response).to redirect_to(prodution_job_url(ProdutionJob.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProdutionJob" do
        expect {
          post prodution_jobs_url, params: { prodution_job: invalid_attributes }
        }.to change(ProdutionJob, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prodution_jobs_url, params: { prodution_job: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prodution_job" do
        prodution_job = ProdutionJob.create! valid_attributes
        patch prodution_job_url(prodution_job), params: { prodution_job: new_attributes }
        prodution_job.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prodution_job" do
        prodution_job = ProdutionJob.create! valid_attributes
        patch prodution_job_url(prodution_job), params: { prodution_job: new_attributes }
        prodution_job.reload
        expect(response).to redirect_to(prodution_job_url(prodution_job))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prodution_job = ProdutionJob.create! valid_attributes
        patch prodution_job_url(prodution_job), params: { prodution_job: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prodution_job" do
      prodution_job = ProdutionJob.create! valid_attributes
      expect {
        delete prodution_job_url(prodution_job)
      }.to change(ProdutionJob, :count).by(-1)
    end

    it "redirects to the prodution_jobs list" do
      prodution_job = ProdutionJob.create! valid_attributes
      delete prodution_job_url(prodution_job)
      expect(response).to redirect_to(prodution_jobs_url)
    end
  end
end
