class Processing < ActiveRecord::Migration[5.1]

  def change

    create_table "production_jobs", id: :serial, comment: "Instances the production flows execution", force: :cascade do |t|
      t.belongs_to :playground,          null: false, comment: "Isolates tenants in a multi-tenancy configuration"
      t.references :business_process,    null: false, comment: "Production job is an instance of a defined business process"
      t.string "code",       limit: 255, null: false, comment: "Code has to be unique in a hierarchical level"
      t.references :status,              null: false, comment: "Defines the status of the job"
      t.belongs_to :owner,               null: false, comment: "All managed objects have a owner"
      t.string "created_by", limit: 255, null: false, comment: "Trace of the user or process who created the record"
      t.string "updated_by", limit: 255, null: false, comment: "Trace of the last user or process who updated the record"
      t.uuid "business_flow_uuid",                    comment: "Unique identifier of the BusinessFlow (Statistical Activity)"
      t.json :parameters,                             comment: "Heritates parameters for the job"
      t.string "version",    limit: 255,              comment: "Version of the deployed production job"
      t.timestamps

      t.index ["business_flow_uuid"], name: "index_production_jobs_on_business_flow_uuid"
    end

    create_table :production_groups, id: :serial,               comment: "Groups executions events toghether (deployed activity)",
      force: :cascade  do |t|
      t.integer "playground_id",      null: false, index: true, comment: "Isolates tenants in a multi-tenancy configuration"
      t.integer "production_job_id",  null: false, index: true, comment: "Defines the job generating these events"
      t.references :production_execution,                       comment: "Production group belongs to a production execution when executed"
      t.references :predecessor,                   index: true, comment: "Traces the previous group in execution"
      t.references :activity,         null: false,              comment: "Production group references and activity"
      t.references :node_type,                                  comment: "Drives the node's behaviour"
      t.references :success_next,                               comment: "Links to the next activity in case of success"
      t.references :failure_next,                               comment: "Links to the next activity in case of failure"
      t.string "code",                              limit: 255, comment: "Code from the activity"
      t.integer "status_id",          null: false,              comment: "Specify the activity status"
      t.json "attached_files",                                  comment: "Specify attachments path and names"
      t.datetime "started_at",                     index: true, comment: "Activity start timestamp"
      t.datetime "reported_at",                                 comment: "Activity last report timestamp"
      t.datetime "ended_at",                                    comment: "Activity end timestamp"
      t.integer "source_records_count", default: 0,             comment: "Number of records in the source"
      t.integer "processed_count",      default: 0,             comment: "Total records processed"
      t.integer "created_count",        default: 0,             comment: "Number of records created"
      t.integer "read_count",           default: 0,             comment: "Number of records read"
      t.integer "updated_count",        default: 0,             comment: "Number of records updated"
      t.integer "deleted_count",        default: 0,             comment: "Number of records deleted"
      t.integer "rejected_count",       default: 0,             comment: "Number of records rejected"
      t.integer "error_count",          default: 0,             comment: "Number of records errors"
      t.text "error_message",                                   comment: "Last error message"
      t.integer :sort_code,                        index: true, comment: "Helps ordering execution links"
      t.integer :execution_sequence,               index: true, comment: "Showa actual execution order"
      t.json :parameters,                                       comment: "Specify parameters for the group"
      t.index ["predecessor_id"], name: "index_production_groups_predecessor"
    end

    create_table "production_events", id: :serial,  comment: "Traces the production flows execution", force: :cascade do |t|
      t.belongs_to :playground,       null: false,  comment: "Isolates tenants in a multi-tenancy configuration"
      t.references :production_group, null: false,  comment: "Production event belongs to a production group"
      t.references :production_execution,           comment: "Production event belongs to a production execution when executed"
      t.references :predecessor,     index: true,   comment: "Traces the previous event in execution"
      t.references :target_object,                  comment: "Specify the target business object"
      t.references :task,             null: false,  comment: "Specify the running task"
      t.references :status,           null: false,  comment: "Specify the task status"
      t.datetime "started_at",       index: true,   comment: "Task start timestamp"
      t.datetime "reported_at",                     comment: "Task last report timestamp"
      t.datetime "ended_at",                        comment: "Task end timestamp"
      t.integer "source_records_count", default: 0, comment: "Number of records in the source"
      t.integer "processed_count",      default: 0, comment: "Total records processed"
      t.integer "created_count",        default: 0, comment: "Number of records created"
      t.integer "read_count",           default: 0, comment: "Number of records read"
      t.integer "updated_count",        default: 0, comment: "Number of records updated"
      t.integer "deleted_count",        default: 0, comment: "Number of records deleted"
      t.integer "rejected_count",       default: 0, comment: "Number of records rejected"
      t.integer "error_count",          default: 0, comment: "Number of records errors"
      t.text "error_message",                       comment: "Last error message"
      t.references :technology,                     comment: "Instance where the production flow was executed (SAS, SAP, Oracle ...)"
      t.integer "execution_sequence",   default: 0, comment: "Seen execution order of steps"
      t.text "statement",                           comment: "Actual statement executed on the defined technology"
      t.text "return_value",                        comment: "Feedback of the statement action"
      t.references :success_next,                   comment: "Links to the next task in case of success"
      t.references :failure_next,                   comment: "Links to the next task in case of failure"
      t.string "return_value_pattern",  limit: 255, comment: "Format to expect fo return value"
      t.string "completion_message",    limit: 255, comment: "Log completion message"
      t.string "params_file_path",      limit: 255, comment: "Path to the parameters file"
      t.string "params_file_name",      limit: 255, comment: "Parameters file name"
      t.references :statement_language,             comment: "Statement language (OS specific )"
      t.string "git_hash",              limit: 255, comment: "Version management reference"
      t.text "git_response",                        comment: "Version management folder analysis"
      t.references :node_type,                      comment: "Drives the node's behaviour"
      t.string "sort_code",             limit: 255, comment: "Code used for sorting displayed indexes"
      t.json :parameters,                           comment: "Specify parameters for the task"
      t.json "contract_input",                      comment: "Identification and parmeters of the requesting Scheduler step"
      t.json "contract_output",                     comment: "Response and parmeters of the requested script"
      t.string "request_id",            limit: 255, comment: "Request unique concatenated identifier"
      t.string "code",                  limit: 255, comment: "Code from the task"


      t.index ["predecessor_id"], name: "index_production_events_predecessor"
    end

    create_table "production_executions", id: :serial, comment: "links to the production flows iterations", force: :cascade do |t|
      t.belongs_to :playground,       null: false,  comment: "Isolates tenants in a multi-tenancy configuration"
      t.references :production_job,   null: false,  comment: "Defines the job generating these events"
      t.references :environment,                    comment: "Defines in which context it is executed (Dev, Val, Prod or other)"
      t.references :status,           null: false,  comment: "Specify the task status"
      t.boolean :is_for_test,      default: false,  comment: "Flag to allow step by step execution and statements modification"
      t.datetime "started_at",                      comment: "Task start timestamp"
      t.datetime "reported_at",                     comment: "Task last report timestamp"
      t.datetime "ended_at",                        comment: "Task end timestamp"
      t.integer "source_records_count", default: 0, comment: "Number of records in the source"
      t.integer "processed_count",      default: 0, comment: "Total records processed"
      t.integer "created_count",        default: 0, comment: "Number of records created"
      t.integer "read_count",           default: 0, comment: "Number of records read"
      t.integer "updated_count",        default: 0, comment: "Number of records updated"
      t.integer "deleted_count",        default: 0, comment: "Number of records deleted"
      t.integer "rejected_count",       default: 0, comment: "Number of records rejected"
      t.integer "error_count",          default: 0, comment: "Number of records errors"
      t.text "error_message",                       comment: "Last error message"
      t.json :parameters,                           comment: "Specify parameters for the execution"
      t.belongs_to :owner,            null: false,  comment: "All managed objects have a owner"
      t.string "message_id",            limit: 255, comment: "Identifier of message queue message if any"
      t.string "code",                  limit: 255, comment: "Code from the schedule"
      t.timestamps
    end

    create_table "production_schedules", id: :serial, comment: "Provides the planning to production flows execution", force: :cascade do |t|
      t.belongs_to :playground,         null: false,  comment: "Isolates tenants in a multi-tenancy configuration"
      t.references :production_job,     null: false,  comment: "Specify the process to be executed"
      t.references :environment,                      comment: "Defines in which context it is executed (Dev, Val, Prod or other)"
      t.references :mode,                             comment: "Scheduling mode (Test, at date, queue, interval)"
      t.string     :code,    limit: 255,              comment: "Small information label for the schedule"
      t.datetime "active_from", default: -> { "CURRENT_DATE" }, comment: "Validity period"
      t.datetime "active_to"
      t.references :status,     default: 1,           comment: "Active or Inactive flag"
      t.integer "repeat_value", default: 0,           comment: "Run x times based on this value"
      t.integer "repeat_interval",                    comment: "Repetition interval value"
      t.integer :run_on_nth,                          comment: "Nth day for repetition"
      t.references :run_on_day,                       comment: "Day for execution"
      t.references :period_type_id,                   comment: "Periodicity"
      t.references :within_period_id,                 comment: "Time period for repetition"
      t.references :repeat_interval_unit,             comment: "Repetition interval type (count, day, week, mont, year)"
      t.integer "repeat_counter", default: 0,         comment: "Counts the number of executions"
      t.datetime :last_run,                           comment: "Last execution date and time"
      t.datetime :next_run,                           comment: "Next execution date and time"
      t.datetime :average_duration,                   comment: "Indicator of average executionduration"
      t.belongs_to :owner,               null: false, comment: "All managed objects have a owner"
      t.string "created_by", limit: 255, null: false, comment: "Trace of the user or process who created the record"
      t.string "updated_by", limit: 255, null: false, comment: "Trace of the last user or process who updated the record"
      t.json :parameters,                             comment: "Override parameters for the schedule"
      t.string :queue_name,                           comment: "RabbitMQ queue name"
      t.string :queue_exchange,                       comment: "RabbitMQ message provider"
      t.string :queue_key,                            comment: "RabbitMQ queue key"
      t.json :queue_payload,                          comment: "RabbitMQ queue message"
      t.string "message_identifier",      limit: 255, comment: "Name of the parameter used as identifier in the message Payload"
      t.timestamps
    end

  end
end
